name: "Roam Research Backup"

on:
  push:
    branches:
      - master
  schedule:
    -   cron: "3 */5 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 15
    steps:
      -   uses: actions/checkout@v2
      -   name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

      -   name: Setup dependencies
          run: |
            wget -qO /tmp/jet.zip https://github.com/borkdude/jet/releases/download/v0.0.13/jet-0.0.13-linux-amd64.zip
            unzip /tmp/jet.zip -d /tmp
            sudo mv /tmp/jet /usr/local/bin/jet
            pip install git+https://github.com/adithyabsk/roam-to-git.git
      -   name: Run backup
          run: |
            roam-to-git --skip-git -f edn -- .
          env:
            ROAMRESEARCH_USER: ${{ secrets.ROAMRESEARCH_USER }}
            ROAMRESEARCH_PASSWORD: ${{ secrets.ROAMRESEARCH_PASSWORD }}
            ROAMRESEARCH_DATABASE: ${{ secrets.ROAMRESEARCH_DATABASE }}

      -   name: Commit Changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Automated snapshot ${{ github.run_number }}
